"""create subscriptions copies reservations fines

Revision ID: 3c8661cc4a77
Revises: c1d95a029f4d
Create Date: 2026-10-06 22:58:09.697993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8661cc4a77'
down_revision: Union[str, Sequence[str], None] = 'c1d95a029f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_copies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('inventory_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'ISSUED', 'LOST', 'WRITTEN_OFF', name='copystatus', native_enum=False, length=20), server_default='AVAILABLE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('AVAILABLE', 'RESERVED', 'ISSUED', 'LOST', 'WRITTEN_OFF')", name=op.f('ck_book_copies_copy_status')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_copies_book_id_books'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_copies')),
    sa.UniqueConstraint('inventory_number', name=op.f('uq_book_copies_inventory_number'))
    )
    op.create_index(op.f('ix_book_copies_book_id'), 'book_copies', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_copies_status'), 'book_copies', ['status'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('copy_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ISSUED', 'RETURNED', 'CANCELLED', 'EXPIRED', 'LOST', name='reservationstatus', native_enum=False, length=20), server_default='CREATED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pickup_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('CREATED', 'ISSUED', 'RETURNED', 'CANCELLED', 'EXPIRED', 'LOST')", name=op.f('ck_reservations_reservation_status')),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], name=op.f('fk_reservations_copy_id_book_copies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reservations_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.create_index(op.f('ix_reservations_copy_id'), 'reservations', ['copy_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_index('uq_reservations_copy_active', 'reservations', ['copy_id'], unique=True, postgresql_where=sa.text("status IN ('CREATED', 'ISSUED')"))
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', name='subscriptionstatus', native_enum=False, length=20), server_default='ACTIVE', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'EXPIRED')", name=op.f('ck_subscriptions_subscription_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index('uq_subscriptions_user_active', 'subscriptions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('fines',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('reservation_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Enum('LATE_RETURN', 'LOST', name='finereason', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', name='finestatus', native_enum=False, length=20), server_default='UNPAID', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reason IN ('LATE_RETURN', 'LOST')", name=op.f('ck_fines_fine_reason')),
    sa.CheckConstraint("status IN ('UNPAID', 'PAID')", name=op.f('ck_fines_fine_status')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_fines_reservation_id_reservations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fines')),
    sa.UniqueConstraint('reservation_id', 'reason', name='uq_fines_reservation_reason')
    )
    op.create_index(op.f('ix_fines_reservation_id'), 'fines', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fines_reservation_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index('uq_subscriptions_user_active', table_name='subscriptions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('uq_reservations_copy_active', table_name='reservations', postgresql_where=sa.text("status IN ('CREATED', 'ISSUED')"))
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_copy_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_book_copies_status'), table_name='book_copies')
    op.drop_index(op.f('ix_book_copies_book_id'), table_name='book_copies')
    op.drop_table('book_copies')
    # ### end Alembic commands ###
