"""create assotiations user_book_relations authors

Revision ID: 9a9b885639a5
Revises: 3c8661cc4a77
Create Date: 2026-10-07 03:07:36.003293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9b885639a5'
down_revision: Union[str, Sequence[str], None] = '3c8661cc4a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors')),
    sa.UniqueConstraint('full_name', name=op.f('uq_authors_full_name'))
    )
    op.create_table('genres',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('book_author',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_book_author_author_id_authors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_author_book_id_books'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_author')),
    sa.UniqueConstraint('book_id', 'author_id', name='uq_assoc_book_author')
    )
    op.create_table('book_genre',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_genre_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_book_genre_genre_id_genres'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_genre')),
    sa.UniqueConstraint('book_id', 'genre_id', name='uq_assoc_book_genre')
    )
    op.create_table('rating',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_rating_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rating_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating')),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_rating_user_book')
    )
    op.create_table('reading_progress',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.BigInteger(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reading_progress_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reading_progress_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_progress')),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_readingprogress_user_book')
    )
    op.create_table('user_genre',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_user_genre_genre_id_genres'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_genre_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_genre')),
    sa.UniqueConstraint('user_id', 'genre_id', name='uq_assoc_user_genre')
    )
    op.create_table('wishlist_item',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_wishlist_item_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wishlist_item_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlist_item')),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_wishlistitem_user_book')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_item')
    op.drop_table('user_genre')
    op.drop_table('reading_progress')
    op.drop_table('rating')
    op.drop_table('book_genre')
    op.drop_table('book_author')
    op.drop_table('genres')
    op.drop_table('authors')
    # ### end Alembic commands ###
