"""create roles users books

Revision ID: e1d248c560c2
Revises: 
Create Date: 2026-10-05 13:34:52.167770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models import RoleTypes, UserStatus, BookStatus, AccessType


# revision identifiers, used by Alembic.
revision: str = 'e1d248c560c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('access_type', sa.Enum(AccessType, native_enum=False, length=20), server_default=AccessType.NONE.value, nullable=False),
    sa.Column('status', sa.Enum(BookStatus, native_enum=False, length=20), server_default=BookStatus.DRAFT.value, nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    roles_table = op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Enum(RoleTypes, native_enum=False, length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.bulk_insert(roles_table,
        [
            {'name': RoleTypes.ADMIN.value},
            {'name': RoleTypes.LIBRARIAN.value},
            {'name': RoleTypes.READER.value},
        ]
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum(UserStatus, native_enum=False, length=20), server_default=UserStatus.ACTIVE.value, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('books')
    # ### end Alembic commands ###
